language: node_js
node_js:
  - "10.5.0"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
